### ISSUE TITLE
Setting Overprint Mode to 1  not permitted in PDF/A-2, reverting to normal PDF output

### ISSUE THREAD

**Issue by libelle17** [jbarlow83/OCRmyPDF#107]
In Fedora24, per default ghostscript 9.20 ist installed via the repository.
If I install ocrmypdf 4.3.1 here and invoke the command 
`ocrmypdf Kopie2.pdf Kopie2.pdf`
I get the error message:

> GPL Ghostscript 9.20: Setting Overprint Mode to 1
 not permitted in PDF/A-2, reverting to normal PDF output
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 11, in <module>
    sys.exit(run_pipeline())
  File "/usr/lib/python3.5/site-packages/ocrmypdf/__main__.py", line 1520, in run_pipeline
    pdfa_info = file_claims_pdfa(options.output_file)
  File "/usr/lib/python3.5/site-packages/ocrmypdf/pdfa.py", line 146, in file_claims_pdfa
    part_conformance = pdfa_dict['part'] + pdfa_dict['conformance']
KeyError: 'part'
> 
After downgrading to ghostscript 9.16, the error disappears.
[Kopie2.pdf](https://github.com/jbarlow83/OCRmyPDF/files/580642/Kopie2.pdf)

**Comment by jbarlow83** [comment]
The exception happens because 4.3.1 doesn't handle the failure path correctly, which I will fix.

Alternately, you can also use ``-output-type pdf`` to skip PDF/A conversion, if that is not important to you - see the documentation for why you might need/want it.

The PDF you supplied already contains recognized OCR text, which as the message indicates, is indeed marked for overprinting, a PDF feature only relevant to printing documents with multiple ink layers. From my testing it appears that Ghostscript 9.19 (and probably <9.19) is responsible for incorrectly inserting this command, and then Ghostscript 9.20 refuses to work with it.

After I fix the exception handling bug you should be able to use Ghostscript 9.20 on files were not previously converted to PDF/A by an earlier Ghostscript.

**Comment by libelle17** [comment]
I thank You for the quick analysis and response and in advance for the fixing!

**Comment by jbarlow83** [comment]
Fixed in 4.3.2

**Comment by azrdev** [comment]
using 4.3.2. with ghostscript 9.20 on archlinux, this still happens: 
~~~
GPL Ghostscript 9.20: Setting Overprint Mode to 1
 not permitted in PDF/A-2, reverting to normal PDF output
WARNING - Output file is okay but is not PDF/A (seems to be No XMP metadata)
~~~

**Comment by jbarlow83** [comment]
Seems I still had further work to do this on.

4.3.3 should improve the situation and generate a PDF/A correctly. Ghostscript still prints a warning/error about suppressing overprint mode, but you can safely ignore that.

**Comment by EtienneFerrandi** [comment]
I recently have this problem.
```
ERROR - GPL Ghostscript 9.50: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.50: ERROR: ioerror (-12) on closing pdfwrite device.
  ERROR - An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 391, in run_pipeline
    exec_concurrent(context)
  File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 320, in exec_concurrent
    pdf = post_process(pdf, context)
  File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 177, in post_process
    pdf_out = metadata_fixup(pdf_out, context)
  File "/usr/lib/python3/dist-packages/ocrmypdf/_pipeline.py", line 751, in metadata_fixup
    with pikepdf.open(context.origin) as original, pikepdf.open(working_file) as pdf:
  File "/usr/lib/python3/dist-packages/pikepdf/__init__.py", line 71, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /tmp/com.github.ocrmypdf._3c3u5ow/pdfa.pdf: unable to find trailer dictionary while recovering damaged file
```

**Comment by jbarlow83** [comment]
@EtienneFerrandi - please open a new issue with all of the requested details, and provide an example file if possible. Unlikely to be related to a 5 year old issue.
