### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#526]
In case I want to update ocrmypdf to the latest version on ubuntu 18.04, I first have to uninstall the old version first. Could be added to the installation documentation.
Thanks, Femi

**Comment by jbarlow83** [comment]
Fixed for v9.7.1

**Comment by femifrak** [comment]
The installation instruction still do not work. I did not mean that the system's ocrmypdf should be deinstalled first, but the "pip version". This is required first:
 python3 -m pip uninstall ocrmypdf
