### ISSUE TITLE
An exception occurred while executing the pipeline

### ISSUE THREAD

**Issue by meljturner** [jbarlow83/OCRmyPDF#591]
**Describe the bug**
OCRmyPDF fails on many different files with the same error; traceback as follows:
Scanning contents: 100%|████████████████████████| 1/1 [00:00<00:00, 56.98page/s]
Using Tesseract OpenMP thread limit 3
OCR: 100%|██████████████████████████████████| 1.0/1.0 [00:00<00:00,  2.56page/s]
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/10.2.0/libexec/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 356, in run_pipeline
    exec_concurrent(context)
  File "/usr/local/Cellar/ocrmypdf/10.2.0/libexec/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 293, in exec_concurrent
    pdf = post_process(pdf, context)
  File "/usr/local/Cellar/ocrmypdf/10.2.0/libexec/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 234, in post_process
    pdf_out = metadata_fixup(pdf_out, context)
  File "/usr/local/Cellar/ocrmypdf/10.2.0/libexec/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 766, in metadata_fixup
    del meta['dc:title']
  File "/usr/local/Cellar/ocrmypdf/10.2.0/libexec/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 389, in __exit__
    self._apply_changes()
  File "/usr/local/Cellar/ocrmypdf/10.2.0/libexec/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 455, in _apply_changes
    self._update_docinfo()
  File "/usr/local/Cellar/ocrmypdf/10.2.0/libexec/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 411, in _update_docinfo
    value = converter.docinfo_from_xmp(value)
  File "/usr/local/Cellar/ocrmypdf/10.2.0/libexec/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 172, in docinfo_from_xmp
    return '; '.join(xmp_val)
TypeError: sequence item 0: expected str instance, NoneType found

**To Reproduce**
What command line or API call were you trying to run?

```bash
ocrmypdf  --skip-text input.pdf output.pdf
```

**Example file**
https://burntlands.ca/2015-11-12RynoMotors.pdf

**Expected behavior**
I have ocr'd similar files using the same scanner and command
**System**
 - OS:MacOS 10.15.5
 - OCRmyPDF Version: 10.2.0 (homebrew)
 - How did you install ocrmypdf? homebrew

**Comment by jbarlow83** [comment]
This issue should be fixed with pikepdf 1.16.1 or newer, but Homebrew is currently installing an older version of pikepdf. You could wait for Homebrew to update ocrmypdf or try making the change yourself.

**Comment by jbarlow83** [comment]
Crossref: https://github.com/pikepdf/pikepdf/issues/84

**Comment by meljturner** [comment]
According to Homebrew, they are already using pikpdf  1.16.1. I reinstalled from source but error still occurs. Thanks for this; most of my use cases work perfectly.
Mel Turner

meljturner@burntlands.ca <mailto:meljturner@burntlands.ca>
160 Fairbairn Bros. St.
Almonte, Ont.
K0A 1A0
613-322-5231

**Comment by jbarlow83** [comment]
GitHub posted your phone number and email address from your signature here. I removed it.

Homebrew has not applied the fix yet in the latest version of their formula for ocrmypdf, as of this writing:
https://github.com/Homebrew/homebrew-core/blob/1e61ec21b84238138d9931de859a00769022701d/Formula/ocrmypdf.rb#L72

Using the latest version of pikepdf on my machine, the file you provided is processed without error.

**Comment by meljturner** [comment]
Thanks. I have scrapped and reinstalled my Python setup using pyenv and not using Homebrew. I agree the problem is resolved. 

Please close the issue
