### ISSUE TITLE
ocrmypdf 11.4.4 failed to build on apple silicon

### ISSUE THREAD

**Issue by chenrui333** [jbarlow83/OCRmyPDF#709]
**Describe the bug**
ocrmypdf 11.4.4 failed to build on apple silicon

build error message ([run log url](https://github.com/Homebrew/homebrew-core/runs/1636099742)):
```
==> /opt/homebrew/Cellar/ocrmypdf/11.4.4/bin/ocrmypdf -f -q --deskew /opt/homebrew/Library/Homebrew/test/support/fixtures/test.pdf ocr.pdf
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ocrmypdf/11.4.4/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/opt/homebrew/Cellar/ocrmypdf/11.4.4/libexec/lib/python3.9/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/opt/homebrew/Cellar/ocrmypdf/11.4.4/libexec/lib/python3.9/site-packages/ocrmypdf/leptonica.py", line 174, in <module>
    def _stderr_handler(cstr):
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

**To Reproduce**
pip installation and run on darwin arm64 system?

**Expected behavior**
build successfuly

**System (please complete the following information):**
 - OS: OSX darwin arm64
 - Python version: python 3.9
 - OCRmyPDF version: Ocrmypdf 11.4.4

**Additional context**
relates to https://github.com/Homebrew/homebrew-core/pull/68159

**Comment by jbarlow83** [comment]
There is no continuous integration service that makes Apple ARM VMs available, and since I don't own the hardware I will need you to test it.

We'll throw in a platform specific hack. Can you run this so I can make sure I can detect ARM?
```
python3 -c 'import platform; print(f"{platform.system()=} {platform.machine()=} {platform.processor()=}")'
```

**Comment by jbarlow83** [comment]
If you can, please checkout the branch `apple-silicon-fix` to see if this resolves the issue. The ocrmypdf documentation explains how to install directly from github.

**Comment by jbarlow83** [comment]
I merged the fix into master because I'm somewhat confident that will take of it for now.

**Comment by WilkinsonProducts** [comment]
Still not able to install OCRMYPDF on Big Sur on Silicon.  Breaks on the start of this area. 

==> /opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/bin/pip install -v --no-deps --
Last 15 lines from /Users/t/Library/Logs/Homebrew/ocrmypdf/06.pip:
  File "/opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 534, in _generate_metadata
    return generate_metadata(
  File "/opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 34, in generate_metadata

Have no problem building it on Big Sur on intel just not on this. Am using this command brew install --build-from-source ocrmypdf to build it as the command brew install ocrmypdf says no bottle available. 

Would be happy to run any commands on this machine if that helps as long as you tell me what to do and what you need back.

Did not know if you every got an answer back on your question above on but I ran it and this is what you get back. 
t ~ % python3 -c 'import platform; print(f"{platform.system()=} {platform.machine()=} {platform.processor()=}")'
platform.system()='Darwin' platform.machine()='arm64' platform.processor()='arm'

**Comment by jbarlow83** [comment]
Can you provide all of `/Users/t/Library/Logs/Homebrew/ocrmypdf/`? 

Those last two lines unfortunately don't help much - if anything they are saying the problem is in pip.

**Comment by WilkinsonProducts** [comment]
I think this is what you wanted.

**Comment by jbarlow83** [comment]
Unfortunately Github doesn't upload attachments sent by email; you have to login and upload them.

**Comment by WilkinsonProducts** [comment]
I will do that later, thanks for letting me know. My wife grabbed that
machine for some photos but will send them up later tonight.

Once I am logged in will it all me to move a zip up with all the text files
or will I have to put them up individual.

Regards TOm

**Comment by WilkinsonProducts** [comment]
Here is that file with the text files in it.

[Archive.zip](https://github.com/jbarlow83/OCRmyPDF/files/5907550/Archive.zip)

**Comment by jbarlow83** [comment]
Here are some interesting excerpts from 06.pip:

```
  Running command /opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/bin/python3 /opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/tmp/tmphpdxj_9i

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      =============================DEBUG ASSISTANCE=============================
...

ImportError: dlopen(/private/tmp/pip-build-env-6xf2zy6b/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
      Referenced from: /private/tmp/pip-build-env-6xf2zy6b/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
      Expected in: flat namespace
     in /private/tmp/pip-build-env-6xf2zy6b/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
    Preparing wheel metadata: finished with status 'error'
WARNING: Discarding file:///private/tmp/ocrmypdf--cryptography-20210201-47873-ud9n8o/cryptography-3.3.1. Command errored out with exit status 1: /opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/bin/python3 /opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmpo7nk0hv0 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/bin/python3 /opt/homebrew/Cellar/ocrmypdf/11.6.0/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmpo7nk0hv0 Check the logs for full command output.

...
```

The breakdown is for the dependency `pdfminer.six` requires `cryptography`, which in turn requires `cffi`. ocrmypdf is the sole user of `pdfminer.six` in Homebrew, so the situation is unique.

`fdroidserver` also requires `cryptography` and `Pillow`, and works on ARM, for which it needs custom build steps. Based on what was done there, you could try the following, but it is a stab in the dark

```diff
diff --git a/Formula/ocrmypdf.rb b/Formula/ocrmypdf.rb
index ac0091ecee..78785646f8 100644
--- a/Formula/ocrmypdf.rb
+++ b/Formula/ocrmypdf.rb
@@ -144,7 +144,9 @@ class Ocrmypdf < Formula
     # Fix "ld: file not found: /usr/lib/system/libsystem_darwin.dylib" for lxml
     ENV["SDKROOT"] = MacOS.sdk_path if MacOS.version == :sierra

-    res = resources.map(&:name).to_set - ["Pillow"]
+    venv.pip_install resource("cffi")
+
+    res = resources.map(&:name).to_set - %w[cffi Pillow]
     res.each do |r|
       venv.pip_install resource(r)
     end
```

**Comment by wrobelda** [comment]
@jbarlow83 same issue here, just tried your suggestion but still getting the same error.

**Comment by jbarlow83** [comment]
Thanks for checking.

**Comment by lucas-clemente** [comment]
I'm also on an M1, and I'm getting the same error when trying to build via homebrew. I did manage to get it working using plain pip:

```
$ pip3 install --user ocrmypdf
# didn't work (don't have the logs anymore, but I think it was the same issue)
$ pip3 install --upgrade pip
$ pip3 install --user ocrmypdf
# worked :)
```

I don't know enough about python or homebrew to say what the exact issue is – maybe updating pip fixed it?

(Also, my setup may be weird, pip3 is homebrew's, but ocrmypdf got installed in `~/Library/Python/3.9/bin/ocrmypdf`...)

**Comment by jbarlow83** [comment]
Since it works on pip we're probably looking at a Homebrew specific issue.

**Comment by WilkinsonProducts** [comment]
These did not work for me on pip at all.  The command  pip3 install
--upgrade pip said it was already done. The pip3 install --user ocrmypdf
command had errors all over.

**Comment by jbarlow83** [comment]
I do appreciate the ongoing feedback, but I want to be clear the community will need to solve this because I don't have M1 hardware. (And I won't unless there's an M1 laptop with magsafe, a reasonable number of USB ports, and a SD Card slot - in other words I'm looking for a laptop that is actually superior to my MacBook Pro 2012. I don't think this too much to ask after 9 years. /rant) Or if someone can point me to some sort of M1 VM, I could investigate.

**Comment by WilkinsonProducts** [comment]
No problem, I have some intel machines I am able to run the ocrmypdf in the
meantime so for me no issues. Dealing with some issues with Big Sur in the
meantime. thanks for your time

**Comment by ltgustavsen** [comment]
I just did a pip3 install --user ocrmypdf and It worked very well on a M1 Air. 😀

```
ltg@Larss-MacBook-Air:~/Downloads$ uname -a
Darwin Larss-MacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
ltg@Larss-MacBook-Air:~/Downloads$ '/Users/ltg/Library/Python/3.9/bin/ocrmypdf'  --version
11.7.0


```
[ocrmypdf.txt](https://github.com/jbarlow83/OCRmyPDF/files/6064194/ocrmypdf.txt)

**Comment by jiangtianli91** [comment]
I installed ocrmypdf with pip. And installed tesseract with homebrew on my m1 macbook. But it produced this error:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/opt/homebrew/lib/python3.9/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/opt/homebrew/lib/python3.9/site-packages/ocrmypdf/leptonica.py", line 29, in <module>
    from ocrmypdf.lib._leptonica import ffi
  File "/opt/homebrew/lib/python3.9/site-packages/ocrmypdf/lib/_leptonica.py", line 2, in <module>
    import _cffi_backend
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
```

**Comment by jiangtianli91** [comment]
I was using pip3 in opt/homebrew folder. 
I think the problem is that opt/homebrew arm64 python3 is still importing x86 python cffi.
The related explanation is here: https://github.com/pyca/cryptography/issues/5742#issuecomment-778573539
I fixed it by remove my whole x86 homebrew...

**Comment by ltgustavsen** [comment]
Nice.
I also noticed today that brew had a new version of ocrmypdf. It worked :-)

**Comment by WilkinsonProducts** [comment]
Noticed on Big Sur when using commands from
https://ocrmypdf.readthedocs.io/en/latest/batch.html that on Big Sur they
no longer work on intel or m1 processors.


Sorry if this is the wrong place to send them. New to this stuff.



parallel --tag -j 2 ocrmypdf '{}' 'output/{}' ::: *.pdf



OutputFileAccessError: Output file location (output/2016-02RB 58956996
PW-1.pdf) is not a writable file.


Used to work very nicely but completely screwed up on Big Sur. Got the brew
ocrmypdf to work finally so that seems to be okay.


Regards

**Comment by ltgustavsen** [comment]
Do you have the folder output?
```
mkdir output
parallel --tag -j 2 ocrmypdf '{}' 'output/{}' ::: *.pdf
```

**Comment by jbarlow83** [comment]
I am going to close this issue now since the build is working on brew and people probably don't have to build from source.

Of course, pip install ought work on Apple Silicon too. If there are any new issues related to builds, please open a new issue for that. Thanks to everyone who contributed.
